#version 460 core

#include <guard.glsl>

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(binding = 0, std430)  restrict readonly buffer           b_buffer { vec3 data[]; };
layout(binding = 0, rgba32f) restrict writeonly uniform image2D i_image;
layout(binding = 0, std140)  uniform b_uniform { uvec2 size; };

void main() {
  const uvec2 v = gl_GlobalInvocationID.xy;
  guard(min(v, size - 1) == v);
  imageStore(i_image, ivec2(v), vec4(data[size.x * v.y + v.x], 1));
}