#ifndef RENDER_TRACKING_PARTIAL_GLSL_GUARD
#define RENDER_TRACKING_PARTIAL_GLSL_GUARD

#define ENABLE_PATH_TRACKING
#define ENABLE_PARTIAL_PATH_TRACKING

#include <render/path.glsl>

#endif // RENDER_TRACKING_PARTIAL_GLSL_GUARD