#version 460 core

// Enable necessary subgroup extensions
#extension GL_KHR_shader_subgroup_basic      : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_clustered  : require

#include <guard.glsl>
#include <spectrum_invoc.glsl>
#include <spectrum_cluster.glsl>

// Use shorthand for clustered types
#define Spec ClSpec

layout(local_size_x = 256) in;
layout(std430)             buffer;
layout(std140)             uniform;

layout(binding = 0) restrict readonly  buffer b_0 { InSpec data[]; } b_spec_texture;
layout(binding = 1) restrict writeonly buffer b_1 { uint   data[]; } b_vali_texture;
layout(binding = 0) uniform u_o { uint n; } b_size;

Spec load_spec_texture(uint i) {
  Spec s;
  cl_spec_scatter(s, b_spec_texture.data[i]);
  return s;
}

void main() {
  const uint i = gl_GlobalInvocationID.x / cl_spectrum_invc_n;
  guard(i < b_size.n);

  // Load spectral data from buffer and test spectral values for out-of-bounds-ing
  Spec s = load_spec_texture(i);
  bool b = cl_hmin(s) < 0.f || cl_hmax(s) > 1.f;

  // Store results
  if (cl_bin_elect())
    b_vali_texture.data[i] = b ? 1 : 0;
}